// HQ Loan Collection Statement — mirrors loan_collection_statement2() web view (screenshot 2)
import React, { useState } from 'react';
import { View, Text, ScrollView, StyleSheet, ActivityIndicator, TouchableOpacity, TextInput } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { ScreenLayout } from '@/components/common/ScreenLayout';
import { Colors, Spacing, Typography, Radius } from '@/constants/theme';
import api from '@/lib/api';
import { DateInput } from '@/components/ui/DateInput';

const NAVY = '#0d1b2e'; const GOLD = '#c8a96e'; const TEAL = '#5bc0de';
function fmtN(v: any) { return Math.round(Number(v)||0).toLocaleString('en-US'); }
function fmtDate(d: string) {
  if (!d) return '—';
  const p = d.split('-');
  return p.length === 3 ? `${p[2]}/${p[1]}/${p[0]}` : d;
}
function dayLabel(d: string) {
  if (!d) return '';
  const dt = new Date(d);
  return dt.toLocaleDateString('en-GB', { weekday:'long', day:'2-digit', month:'long', year:'numeric' }).toUpperCase();
}
function fmtGeneratedAt(iso?: string) {
  if (!iso) return '';
  try {
    const dt = new Date(iso);
    return dt.toLocaleDateString('en-GB', { day:'2-digit', month:'2-digit', year:'numeric' }) +
           ' ' + dt.toLocaleTimeString('en-GB', { hour:'2-digit', minute:'2-digit' });
  } catch {
    return '';
  }
}

export default function RepaymentsReportDetail() {
  const { office, date } = useLocalSearchParams<{ office: string; date: string }>();
  const [dateFrom, setDateFrom] = useState(date ?? '');
  const [dateTo,   setDateTo]   = useState(date ?? '');
  const [search,   setSearch]   = useState({ from: date ?? '', to: date ?? '', office: office ?? '' });

  const { data, isLoading } = useQuery({
    queryKey: ['hq-loan-collection', search],
    queryFn:  () => api.get('/hq/loan-collection/', {
      params: { start_date: search.from, end_date: search.to, office: search.office },
    }).then(r => r.data),
  });

  const rows: any[]   = data?.rows ?? [];
  const groups: any[] = data?.groups ?? [];

  // Group rows by date for display
  const rowsByDate: Record<string, any[]> = {};
  rows.forEach(r => {
    if (!rowsByDate[r.date]) rowsByDate[r.date] = [];
    rowsByDate[r.date].push(r);
  });

  return (
    <ScreenLayout title="Loan Collection" subtitle={office} showBack>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }}>
        <View style={s.filterBar}>
          <View style={s.filterRow}>
            <View style={{ flex: 1 }}><Text style={s.filterLabel}>From</Text><DateInput value={dateFrom} onChange={setDateFrom} /></View>
            <View style={{ flex: 1 }}><Text style={s.filterLabel}>To</Text><DateInput value={dateTo} onChange={setDateTo} /></View>
          </View>
          <TouchableOpacity style={s.applyBtn} onPress={() => setSearch({ from: dateFrom, to: dateTo, office: office ?? '' })}>
            <Text style={s.applyBtnText}>Apply Filters</Text>
          </TouchableOpacity>
        </View>

        {isLoading && <ActivityIndicator color={Colors.primary} size="large" style={{ marginTop: 40 }} />}

        {data && (
          <>
            <Text style={s.branchTitle}>{(search.office || 'ALL').toUpperCase()} BRANCH</Text>
            <Text style={s.reportTitle}>LOAN COLLECTION STATEMENT FROM {search.from} TO {search.to}</Text>

            {/* Stats strip — matches screenshot's 6 metric cards exactly */}
            <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginBottom: Spacing.sm }}>
              <View style={s.statsRow}>
                {[
                  { label: 'Transactions',   value: String(data.total_transactions), sub: 'repayment records' },
                  { label: 'Total Principal',value: fmtN(data.total_principal),      sub: 'TZS', color: TEAL },
                  { label: 'Total Interest', value: fmtN(data.total_interest),       sub: 'TZS' },
                  { label: 'Total Collected',value: fmtN(data.total_collected),      sub: 'TZS', color: Colors.success },
                  { label: 'Office',         value: (search.office || 'ALL').toUpperCase(), sub: 'filter' },
                  { label: 'Generated By',   value: data.generated_by ?? 'N/A',      sub: fmtGeneratedAt(data.generated_at) },
                ].map((st) => (
                  <View key={st.label} style={s.statCard}>
                    <Text style={s.statLabel}>{st.label}</Text>
                    <Text style={[s.statVal, st.color && { color: st.color }]} numberOfLines={1}>{st.value}</Text>
                    {st.sub ? <Text style={s.statSub} numberOfLines={1}>{st.sub}</Text> : null}
                  </View>
                ))}
              </View>
            </ScrollView>

            {rows.length === 0 ? (
              <View style={s.emptyBox}><Text style={s.emptyText}>No repayments in this period.</Text></View>
            ) : (
              <ScrollView horizontal showsHorizontalScrollIndicator style={{ marginHorizontal: Spacing.base }}>
                <View style={s.table}>
                  {/* Header */}
                  <View style={[s.row, s.thead]}>
                    {['Date','S/N','Receipt No.','Client Name','Description','Rate','Principal (TZS)','Interest (TZS)','Total (TZS)','Processed By'].map(h => (
                      <Text key={h} style={[s.cell, s.th,
                        h==='Date'       ? {width:90}  :
                        h==='S/N'        ? {width:36,textAlign:'center'} :
                        h==='Receipt No.'? {width:100} :
                        h==='Client Name'? {width:160} :
                        h==='Description'? {width:200} :
                        h==='Rate'       ? {width:60,textAlign:'center'} :
                        h==='Processed By'?{width:130}:
                        {width:110,textAlign:'right'}]}>{h}</Text>
                    ))}
                  </View>

                  {/* Date-grouped rows */}
                  {Object.entries(rowsByDate).map(([dkey, drows]) => (
                    <React.Fragment key={dkey}>
                      {/* Date group header */}
                      <View style={s.dateGroupRow}>
                        <Text style={s.dateGroupText}>{dayLabel(dkey)} — {drows.length} COLLECTIONS</Text>
                      </View>
                      {drows.map((r: any, i: number) => (
                        <View key={r.sn} style={[s.row, i%2===1 && s.rowAlt]}>
                          <Text style={[s.cell,{width:90,color:Colors.textMuted}]}>{fmtDate(r.date)}</Text>
                          <Text style={[s.cell,{width:36,textAlign:'center',color:Colors.textMuted}]}>{r.sn}</Text>
                          <Text style={[s.cell,{width:100,color:Colors.primary}]}>{r.receipt_no}</Text>
                          <View style={{width:160}}>
                            <Text style={[s.cell,{width:160,fontWeight:'700',textTransform:'uppercase'}]} numberOfLines={1}>{r.client_name}</Text>
                            <Text style={[s.cell,{width:160,fontSize:9,color:Colors.textMuted}]}>{r.client_id_label}</Text>
                          </View>
                          <Text style={[s.cell,{width:200,color:Colors.textMuted,fontSize:10}]} numberOfLines={2}>{r.description}</Text>
                          <Text style={[s.cell,{width:60,textAlign:'center'}]}>{r.rate}</Text>
                          <Text style={[s.cell,{width:110,textAlign:'right'}]}>{fmtN(r.principal)}</Text>
                          <Text style={[s.cell,{width:110,textAlign:'right'}]}>{fmtN(r.interest)}</Text>
                          <Text style={[s.cell,{width:110,textAlign:'right',fontWeight:'600'}]}>{fmtN(r.total)}</Text>
                          <Text style={[s.cell,{width:130,color:Colors.textMuted}]} numberOfLines={1}>{r.processed_by}</Text>
                        </View>
                      ))}
                    </React.Fragment>
                  ))}

                  {/* Grand Total */}
                  <View style={[s.row, s.tfoot]}>
                    <Text style={[s.cell, s.tfootText, {width:90+36+100+160+200+60}]}>GRAND TOTAL</Text>
                    <Text style={[s.cell, s.tfootText, {width:110,textAlign:'right',textDecorationLine:'underline'}]}>{fmtN(data.total_principal)}</Text>
                    <Text style={[s.cell, s.tfootText, {width:110,textAlign:'right',textDecorationLine:'underline'}]}>{fmtN(data.total_interest)}</Text>
                    <Text style={[s.cell, s.tfootText, {width:110,textAlign:'right',textDecorationLine:'underline'}]}>{fmtN(data.total_collected)}</Text>
                    <Text style={[s.cell, {width:130}]}> </Text>
                  </View>
                </View>
              </ScrollView>
            )}
          </>
        )}
      </ScrollView>
    </ScreenLayout>
  );
}

const s = StyleSheet.create({
  filterBar: { backgroundColor: Colors.surface, margin: Spacing.base, borderRadius: Radius.lg, padding: Spacing.base, elevation: 2, gap: Spacing.sm },
  filterRow: { flexDirection: 'row', gap: Spacing.sm },
  filterLabel:{ fontSize: 10, fontWeight: '700', color: Colors.textMuted, textTransform: 'uppercase', marginBottom: 4 },
  input: { borderWidth: 1.5, borderColor: Colors.border, borderRadius: Radius.md, paddingHorizontal: 10, paddingVertical: 7, fontSize: 12, color: Colors.text },
  applyBtn: { backgroundColor: NAVY, borderRadius: Radius.md, paddingVertical: 10, alignItems: 'center' },
  applyBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  branchTitle: { textAlign: 'center', fontSize: 12, fontWeight: '700', color: NAVY, textDecorationLine: 'underline', marginTop: Spacing.sm },
  reportTitle: { textAlign: 'center', fontSize: 11, fontWeight: '800', color: NAVY, textDecorationLine: 'underline', marginBottom: Spacing.sm },
  statsRow: { flexDirection: 'row', marginHorizontal: Spacing.base, gap: 8 },
  statCard: { backgroundColor: Colors.surface, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, paddingVertical: 10, paddingHorizontal: 12, minWidth: 110, alignItems: 'center', elevation: 1 },
  statLabel: { fontSize: 9, fontWeight: '700', color: Colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.3, textAlign: 'center', marginBottom: 4 },
  statVal:  { fontSize: 13, fontWeight: '700', color: Colors.text },
  statSub:  { fontSize: 8, color: Colors.textMuted, marginTop: 1 },
  table: { borderRadius: Radius.md, overflow: 'hidden', borderWidth: 1, borderColor: Colors.border },
  row:   { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, paddingHorizontal: 3, borderBottomWidth: 1, borderBottomColor: Colors.border },
  rowAlt:{ backgroundColor: '#f8f9fa' },
  thead: { backgroundColor: TEAL, borderBottomWidth: 2, borderBottomColor: '#4aa8c4' },
  tfoot: { backgroundColor: GOLD, borderBottomWidth: 0 },
  dateGroupRow: { backgroundColor: '#e9ecef', paddingVertical: 6, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: '#dee2e6' },
  dateGroupText: { fontSize: 11, fontWeight: '700', color: '#495057' },
  cell:  { fontSize: 10, color: Colors.text, paddingHorizontal: 3 },
  th:    { color: '#fff', fontWeight: '700', fontSize: 9, textTransform: 'uppercase' },
  tfootText: { color: '#1a1a1a', fontWeight: '800', fontSize: 10 },
  emptyBox:  { padding: 40, alignItems: 'center' },
  emptyText: { color: Colors.textMuted, fontSize: Typography.sizes.sm },
});
